# Generated by Django 3.1.7 on 2021-03-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('player_name1', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('team1', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='csk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_age', models.IntegerField()),
                ('player_name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cricket')),
            ],
        ),
        migrations.AddField(
            model_name='cricket',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game'),
        ),
    ]
